### ISSUE TITLE
Setup qulice

### ISSUE THREAD

**Issue by sigrist** [sigrist/spotify-api#26]

**Comment by 0pdd** [comment]
@sigrist 3 puzzles [#28](https://github.com/sigrist/spotify-api/issues/28), [#29](https://github.com/sigrist/spotify-api/issues/29), [#30](https://github.com/sigrist/spotify-api/issues/30) are still not solved.

**Comment by sigrist** [comment]
Qulice is to much, there is no IDE integration with Eclipse and some rules I don't agree with and is not possible to remove. Using SonarCloud instead. #24
