### ISSUE TITLE
SpotifyConfiguration documentation

### ISSUE THREAD

**Issue by sigrist** [sigrist/spotify-api#7]
add documentation

**Comment by 0pdd** [comment]
@sigrist the puzzle [#8](https://github.com/sigrist/spotify-api/issues/8) is still not solved.

**Comment by 0pdd** [comment]
@sigrist the only puzzle [#8](https://github.com/sigrist/spotify-api/issues/8) is solved here.

**Comment by 0pdd** [comment]
@sigrist 2 puzzles [#11](https://github.com/sigrist/spotify-api/issues/11), [#12](https://github.com/sigrist/spotify-api/issues/12) are still not solved; solved: [#8](https://github.com/sigrist/spotify-api/issues/8).

**Comment by 0pdd** [comment]
@sigrist all 3 puzzles are solved here: [#11](https://github.com/sigrist/spotify-api/issues/11), [#12](https://github.com/sigrist/spotify-api/issues/12), [#8](https://github.com/sigrist/spotify-api/issues/8).
